spring.application.name=LogFileWatcherWithRedis

log.file.path=/Users/jatinmishra/Desktop/practice/BackendImplementations/src/main/java/org/example/LogFileWatcherWithRedis/src/main/resources/tmp/app.log
log.file.lines=20
log.file.bufferSize=4096


spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=
spring.data.redis.database=0
spring.data.redis.timeout=60000
spring.data.redis.connect-timeout=60000