spring.application.name=LogFileWatcher

logwatcher.file-path=/Users/jatinmishra/Desktop/practice/BackendImplementations/src/main/java/org/example/LogFileWatcher/src/main/resources/app.log
logwatcher.tail-lines=5
logwatcher.template=logs
